/**
 * ICS4UR Computer Science, 12
 * Brampton, Canada
 *
 * https://github.com/SamAssareymuriyil
 * https://repl.it/@SamTheMan/
 *
 * modified     20201008
 * date         20201008
 * @filename    ChangeProject.java
 * @author      Sam Assareymuriyil
 * @version     1.0
 * @see         ChangeProject program Assignment 1.4.1
 */

public class ChangeProject extends javax.swing.JFrame {
    /**
     * Creates new form ChangeApp
     */
    public ChangeProject() {
        initComponents();
        // src: https://www.java-examples.com/show-or-hide-jlabel-example
        errLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtQuarters1 = new javax.swing.JTextField();
        lblChangeExchangeTitle = new javax.swing.JLabel();
        lblEnterCurrency = new javax.swing.JLabel();
        lblAmountUnderCurrency = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtCurrency = new javax.swing.JTextField();
        lblAmount = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        lblQuarters = new javax.swing.JLabel();
        lblDimes = new javax.swing.JLabel();
        lblNickels = new javax.swing.JLabel();
        lblPennies = new javax.swing.JLabel();
        txtQuarters = new javax.swing.JTextField();
        txtNickels = new javax.swing.JTextField();
        txtDimes = new javax.swing.JTextField();
        txtPennies = new javax.swing.JTextField();
        lblToonies = new javax.swing.JLabel();
        txtToonies = new javax.swing.JTextField();
        lblLoonies = new javax.swing.JLabel();
        txtLoonies = new javax.swing.JTextField();
        errLabel = new javax.swing.JLabel();

        txtQuarters1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblChangeExchangeTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblChangeExchangeTitle.setForeground(new java.awt.Color(255, 0, 102));
        lblChangeExchangeTitle.setText("Change Exchange");

        lblEnterCurrency.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEnterCurrency.setText("Enter Currency");

        lblAmountUnderCurrency.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAmountUnderCurrency.setText("Amount (xxxx.xx)");

        btnCalculate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        txtCurrency.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAmount.setText("Amount");

        txtAmount.setEditable(false);
        txtAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblQuarters.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQuarters.setText("Quarters");

        lblDimes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDimes.setText("Dimes");

        lblNickels.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNickels.setText("Nickels");

        lblPennies.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPennies.setText("Pennies");

        txtQuarters.setEditable(false);
        txtQuarters.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtNickels.setEditable(false);
        txtNickels.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDimes.setEditable(false);
        txtDimes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtPennies.setEditable(false);
        txtPennies.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblToonies.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblToonies.setText("Toonies");

        txtToonies.setEditable(false);
        txtToonies.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblLoonies.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLoonies.setText("Loonies");

        txtLoonies.setEditable(false);
        txtLoonies.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        errLabel.setForeground(new java.awt.Color(255, 0, 51));
        errLabel.setText("Error, please try again");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(lblChangeExchangeTitle))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAmountUnderCurrency)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCalculate)
                                            .addComponent(lblEnterCurrency))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(txtCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(errLabel))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(lblAmount)
                                .addGap(18, 18, 18)
                                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblToonies)
                                .addGap(13, 13, 13)
                                .addComponent(txtToonies, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLoonies)
                                .addGap(13, 13, 13)
                                .addComponent(txtLoonies, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQuarters)
                            .addComponent(lblDimes))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuarters, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDimes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPennies)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPennies, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNickels)
                                .addGap(28, 28, 28)
                                .addComponent(txtNickels, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblChangeExchangeTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterCurrency)
                    .addComponent(txtCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAmountUnderCurrency)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculate)
                    .addComponent(btnExit)
                    .addComponent(errLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmount)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuarters)
                    .addComponent(lblNickels)
                    .addComponent(txtQuarters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNickels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblToonies)
                    .addComponent(txtToonies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLoonies)
                        .addComponent(txtLoonies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDimes)
                        .addComponent(lblPennies)
                        .addComponent(txtDimes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPennies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0); // Exit the application.
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        //src: https://www.w3schools.com/java/java_try_catch.asp
        try {
            String amountIn; // the currency
            int total, toonies, loonies, quarters, dimes, nickels, pennies;
            double convertIn;

            amountIn = txtCurrency.getText();
            // Convert the amount from $ to cents.
            convertIn = Double.parseDouble(amountIn) * 100;
            // Truncate all the decimals that come after cents.
            total = (int) convertIn;

            // Calculate the number of toonies.
            toonies = total / 200;
            total = total - (toonies * 200);
            // Calculate the number of loonies.
            loonies = total / 100;
            total = total - (loonies * 100);
            // Calculate the number of quarters.
            quarters = total / 25;
            total = total - (quarters * 25);
            // Calculate the number of dimes.
            dimes = total / 10;
            total = total - (dimes * 10);
            // Calculate the number of nickels.
            nickels = total / 5;
            total = total - (nickels * 5);
            // Calculate the number of pennies.
            pennies = total;

            // Output the input amount.
            txtAmount.setText(amountIn);
            // Output the number of toonies.
            txtToonies.setText(Integer.toString(toonies));
            // Output the number of loonies.
            txtLoonies.setText(Integer.toString(loonies));
            // Output the number of quarters.
            txtQuarters.setText(Integer.toString(quarters));
            // Output the number of dimes.
            txtDimes.setText(Integer.toString(dimes));
            // Output the number of nickels.
            txtNickels.setText(Integer.toString(nickels));
            // Output the number of pennies.
            txtPennies.setText(Integer.toString(pennies));
            errLabel.setVisible(false);
            System.out.println("calculated for $" + amountIn);
        }
        catch (Exception e){
            errLabel.setVisible(true);
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnExit;
    public javax.swing.JLabel errLabel;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblAmountUnderCurrency;
    private javax.swing.JLabel lblChangeExchangeTitle;
    private javax.swing.JLabel lblDimes;
    private javax.swing.JLabel lblEnterCurrency;
    private javax.swing.JLabel lblLoonies;
    private javax.swing.JLabel lblNickels;
    private javax.swing.JLabel lblPennies;
    private javax.swing.JLabel lblQuarters;
    private javax.swing.JLabel lblToonies;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCurrency;
    private javax.swing.JTextField txtDimes;
    private javax.swing.JTextField txtLoonies;
    private javax.swing.JTextField txtNickels;
    private javax.swing.JTextField txtPennies;
    private javax.swing.JTextField txtQuarters;
    private javax.swing.JTextField txtQuarters1;
    private javax.swing.JTextField txtToonies;
    // End of variables declaration//GEN-END:variables
}
